const fs = require('fs');

const newDestinations = [
  // ASIA
  { slug: "phuket", emoji: "🏖", name: "Phuket", country: "Thailand", region: "asia", tier: "gold", views: "8.1B", bg: "#081820", desc: "Pearl of the Andaman", bookingLink: "https://www.booking.com/searchresults.html?ss=Phuket&aid=2311236", tourLink: "https://www.getyourguide.com/phuket-l193/", gearLink: "https://www.amazon.com.au/s?k=phuket+travel+snorkel&tag=rabbitholevid-20", videos: ["Phuket complete guide", "Best beaches Phuket", "Phuket vs Koh Samui", "Budget Phuket tips", "Phuket nightlife", "Island hopping Phuket", "Phuket food guide", "Phi Phi Islands day trip", "Phuket hidden gems", "Phuket travel tips"] },
  { slug: "chiang-mai", emoji: "🐘", name: "Chiang Mai", country: "Thailand", region: "asia", tier: "silver", views: "4.8B", bg: "#1a0800", desc: "Rose of the North", bookingLink: "https://www.booking.com/searchresults.html?ss=Chiang+Mai&aid=2311236", tourLink: "https://www.getyourguide.com/chiang-mai-l193/", gearLink: "https://www.amazon.com.au/s?k=chiang+mai+thailand+travel&tag=rabbitholevid-20", videos: ["Chiang Mai complete guide", "Elephant sanctuary visit", "Night bazaar Chiang Mai", "Chiang Mai food tour", "Doi Inthanon day trip", "Digital nomad Chiang Mai", "Temple hopping guide", "Budget Chiang Mai", "Chiang Mai vs Bangkok", "Hidden gems Chiang Mai"] },
  { slug: "penang", emoji: "🍜", name: "Penang", country: "Malaysia", region: "asia", tier: "silver", views: "3.2B", bg: "#1a0800", desc: "Pearl of the Orient", bookingLink: "https://www.booking.com/searchresults.html?ss=Penang+Malaysia&aid=2311236", tourLink: "https://www.getyourguide.com/penang-l193/", gearLink: "https://www.amazon.com.au/s?k=malaysia+travel+guide&tag=rabbitholevid-20", videos: ["Penang food guide best", "George Town street art", "Penang hill trek", "Budget Penang travel", "Penang street food tour", "Batu Ferringhi beach", "Penang vs KL", "Georgetown hidden gems", "Penang hawker food", "Penang travel tips"] },
  { slug: "lombok", emoji: "🌋", name: "Lombok", country: "Indonesia", region: "asia", tier: "silver", views: "2.8B", bg: "#081a10", desc: "Bali's wilder neighbour", bookingLink: "https://www.booking.com/searchresults.html?ss=Lombok+Indonesia&aid=2311236", tourLink: "https://www.getyourguide.com/lombok-l193/", gearLink: "https://www.amazon.com.au/s?k=lombok+indonesia+travel&tag=rabbitholevid-20", videos: ["Lombok complete guide", "Rinjani volcano trek", "Gili Islands guide", "Lombok vs Bali", "Kuta Lombok beaches", "Budget Lombok travel", "Snorkelling Gili T", "Lombok hidden gems", "Sasak culture visit", "Lombok travel tips"] },
  { slug: "bhutan", emoji: "🏔", name: "Bhutan", country: "Bhutan", region: "asia", tier: "silver", views: "2.1B", bg: "#0e1008", desc: "Last Shangri-La", bookingLink: "https://www.booking.com/searchresults.html?ss=Bhutan&aid=2311236", tourLink: "https://www.getyourguide.com/bhutan-l193/", gearLink: "https://www.amazon.com.au/s?k=bhutan+travel+guide+hiking&tag=rabbitholevid-20", videos: ["Bhutan travel guide", "Tiger's Nest monastery", "Bhutan happiness country", "Thimphu city guide", "Bhutan visa explained", "Paro valley guide", "Punakha dzong visit", "Bhutan budget travel", "Bhutan culture guide", "Bhutan travel tips"] },
  { slug: "mekong-vietnam", emoji: "🛶", name: "Mekong Delta", country: "Vietnam", region: "asia", tier: "bronze", views: "1.9B", bg: "#081808", desc: "River of nine dragons", bookingLink: "https://www.booking.com/searchresults.html?ss=Mekong+Delta+Vietnam&aid=2311236", tourLink: "https://www.getyourguide.com/mekong-delta-l193/", gearLink: "https://www.amazon.com.au/s?k=vietnam+mekong+travel&tag=rabbitholevid-20", videos: ["Mekong Delta tour guide", "Floating markets Vietnam", "Can Tho city guide", "Mekong boat trip", "Mekong food guide", "Ben Tre coconut farms", "Day trip from Ho Chi Minh", "Mekong homestay experience", "Mekong Delta photography", "Mekong travel tips"] },

  // EUROPE
  { slug: "cinque-terre", emoji: "🌈", name: "Cinque Terre", country: "Italy", region: "europe", tier: "gold", views: "5.8B", bg: "#0a1a08", desc: "Five villages on a cliff", bookingLink: "https://www.booking.com/searchresults.html?ss=Cinque+Terre&aid=2311236", tourLink: "https://www.getyourguide.com/cinque-terre-l193/", gearLink: "https://www.amazon.com.au/s?k=cinque+terre+italy+travel&tag=rabbitholevid-20", videos: ["Cinque Terre complete guide", "Best village to stay", "Hiking trail guide", "Cinque Terre by boat", "Budget Cinque Terre tips", "Vernazza village tour", "Manarola photography", "Cinque Terre food guide", "Avoiding crowds tips", "Cinque Terre hidden gems"] },
  { slug: "bruges", emoji: "🍺", name: "Bruges", country: "Belgium", region: "europe", tier: "silver", views: "3.4B", bg: "#0e0818", desc: "Venice of the North", bookingLink: "https://www.booking.com/searchresults.html?ss=Bruges+Belgium&aid=2311236", tourLink: "https://www.getyourguide.com/bruges-l193/", gearLink: "https://www.amazon.com.au/s?k=bruges+belgium+travel+guide&tag=rabbitholevid-20", videos: ["Bruges complete guide", "Belgian chocolate tour", "Bruges beer guide", "Canal boat tour", "Bruges hidden gems", "Day trip from Brussels", "Bruges Christmas market", "Bruges on a budget", "Ghent vs Bruges", "Bruges travel tips"] },
  { slug: "kotor", emoji: "🏰", name: "Kotor", country: "Montenegro", region: "europe", tier: "silver", views: "2.6B", bg: "#081020", desc: "Medieval bay jewel", bookingLink: "https://www.booking.com/searchresults.html?ss=Kotor+Montenegro&aid=2311236", tourLink: "https://www.getyourguide.com/kotor-l193/", gearLink: "https://www.amazon.com.au/s?k=montenegro+kotor+travel&tag=rabbitholevid-20", videos: ["Kotor complete guide", "Bay of Kotor views", "Kotor old city walk", "Kotor fortress hike", "Montenegro road trip", "Kotor day trips", "Budget Montenegro tips", "Perast village visit", "Kotor hidden gems", "Montenegro travel tips"] },
  { slug: "madeira", emoji: "🌺", name: "Madeira", country: "Portugal", region: "europe", tier: "silver", views: "3.1B", bg: "#081a08", desc: "Floating garden of the Atlantic", bookingLink: "https://www.booking.com/searchresults.html?ss=Madeira+Portugal&aid=2311236", tourLink: "https://www.getyourguide.com/madeira-l193/", gearLink: "https://www.amazon.com.au/s?k=madeira+portugal+travel&tag=rabbitholevid-20", videos: ["Madeira complete guide", "Levada walks guide", "Funchal city tour", "Madeira food guide", "Pico do Arieiro hike", "Budget Madeira tips", "Madeira vs Azores", "Toboggan ride Madeira", "Madeira hidden gems", "Madeira travel tips"] },
  { slug: "azores", emoji: "🌋", name: "Azores", country: "Portugal", region: "europe", tier: "silver", views: "2.9B", bg: "#081820", desc: "Portuguese island paradise", bookingLink: "https://www.booking.com/searchresults.html?ss=Azores+Portugal&aid=2311236", tourLink: "https://www.getyourguide.com/azores-l193/", gearLink: "https://www.amazon.com.au/s?k=azores+portugal+travel+guide&tag=rabbitholevid-20", videos: ["Azores complete guide", "Sao Miguel island guide", "Azores whale watching", "Hot springs Azores", "Budget Azores travel", "Azores vs Madeira", "Faial island guide", "Azores hiking best", "Azores hidden gems", "Azores travel tips"] },
  { slug: "crete", emoji: "🏛", name: "Crete", country: "Greece", region: "europe", tier: "silver", views: "3.7B", bg: "#1a0e00", desc: "Cradle of civilisation", bookingLink: "https://www.booking.com/searchresults.html?ss=Crete+Greece&aid=2311236", tourLink: "https://www.getyourguide.com/crete-l193/", gearLink: "https://www.amazon.com.au/s?k=crete+greece+travel+guide&tag=rabbitholevid-20", videos: ["Crete complete guide", "Chania old town", "Samaria Gorge hike", "Crete food guide", "Best beaches Crete", "Heraklion palace visit", "Budget Crete travel", "Crete road trip", "Crete hidden gems", "Crete travel tips"] },
  { slug: "amalfi-positano", emoji: "🍋", name: "Positano", country: "Italy", region: "europe", tier: "gold", views: "4.3B", bg: "#0a1a08", desc: "Vertical village of dreams", bookingLink: "https://www.booking.com/searchresults.html?ss=Positano+Italy&aid=2311236", tourLink: "https://www.getyourguide.com/positano-l193/", gearLink: "https://www.amazon.com.au/s?k=positano+amalfi+travel&tag=rabbitholevid-20", videos: ["Positano complete guide", "Positano beaches best", "Getting to Positano", "Budget Positano tips", "Positano boat tours", "Lemon grove hike", "Positano food guide", "Positano photography", "Positano vs Ravello", "Amalfi coast tips"] },

  // AMERICAS
  { slug: "buenos-aires", emoji: "💃", name: "Buenos Aires", country: "Argentina", region: "americas", tier: "gold", views: "5.2B", bg: "#1a0808", desc: "Paris of South America", bookingLink: "https://www.booking.com/searchresults.html?ss=Buenos+Aires&aid=2311236", tourLink: "https://www.getyourguide.com/buenos-aires-l193/", gearLink: "https://www.amazon.com.au/s?k=buenos+aires+argentina+travel&tag=rabbitholevid-20", videos: ["Buenos Aires complete guide", "Tango show Buenos Aires", "La Boca neighbourhood", "Buenos Aires food tour", "Palermo neighbourhood", "Budget Buenos Aires", "Day trips from BA", "Argentine steak guide", "Buenos Aires nightlife", "Buenos Aires hidden gems"] },
  { slug: "tulum", emoji: "🌴", name: "Tulum", country: "Mexico", region: "americas", tier: "gold", views: "4.6B", bg: "#081a10", desc: "Mayan ruins meet beach", bookingLink: "https://www.booking.com/searchresults.html?ss=Tulum+Mexico&aid=2311236", tourLink: "https://www.getyourguide.com/tulum-l193/", gearLink: "https://www.amazon.com.au/s?k=tulum+mexico+travel+snorkel&tag=rabbitholevid-20", videos: ["Tulum complete guide", "Tulum ruins sunrise", "Best cenotes Tulum", "Tulum beach guide", "Budget Tulum tips", "Tulum vs Cancun", "Tulum food guide", "Tulum nightlife", "Tulum hidden gems", "Tulum travel tips"] },
  { slug: "cancun", emoji: "🏖", name: "Cancun", country: "Mexico", region: "americas", tier: "gold", views: "6.1B", bg: "#081820", desc: "Caribbean playground", bookingLink: "https://www.booking.com/searchresults.html?ss=Cancun+Mexico&aid=2311236", tourLink: "https://www.getyourguide.com/cancun-l193/", gearLink: "https://www.amazon.com.au/s?k=cancun+mexico+travel+snorkel&tag=rabbitholevid-20", videos: ["Cancun complete guide", "Cancun hotel zone", "Chichen Itza day trip", "Cancun vs Tulum", "Budget Cancun tips", "Isla Mujeres day trip", "Cancun food guide", "Cancun nightlife", "Cancun snorkelling", "Cancun travel tips"] },
  { slug: "vancouver", emoji: "🏔", name: "Vancouver", country: "Canada", region: "americas", tier: "silver", views: "4.1B", bg: "#081020", desc: "Mountains meet ocean", bookingLink: "https://www.booking.com/searchresults.html?ss=Vancouver+Canada&aid=2311236", tourLink: "https://www.getyourguide.com/vancouver-l193/", gearLink: "https://www.amazon.com.au/s?k=vancouver+canada+travel+guide&tag=rabbitholevid-20", videos: ["Vancouver complete guide", "Whistler day trip", "Stanley Park walk", "Vancouver food tour", "Granville Island guide", "Budget Vancouver tips", "Vancouver Island trip", "Vancouver hiking best", "Vancouver hidden gems", "Vancouver travel tips"] },
  { slug: "sedona", emoji: "🏜", name: "Sedona", country: "USA", region: "americas", tier: "silver", views: "3.3B", bg: "#1a0800", desc: "Red rock spiritual vortex", bookingLink: "https://www.booking.com/searchresults.html?ss=Sedona+Arizona&aid=2311236", tourLink: "https://www.getyourguide.com/sedona-l193/", gearLink: "https://www.amazon.com.au/s?k=sedona+arizona+hiking+gear&tag=rabbitholevid-20", videos: ["Sedona complete guide", "Best hikes Sedona", "Sedona vortex guide", "Red rock sunset spots", "Sedona food guide", "Budget Sedona tips", "Jeep tour Sedona", "Sedona vs Grand Canyon", "Sedona hidden gems", "Sedona travel tips"] },
  { slug: "nashville", emoji: "🎸", name: "Nashville", country: "USA", region: "americas", tier: "silver", views: "3.8B", bg: "#1a0800", desc: "Music city USA", bookingLink: "https://www.booking.com/searchresults.html?ss=Nashville+Tennessee&aid=2311236", tourLink: "https://www.getyourguide.com/nashville-l193/", gearLink: "https://www.amazon.com.au/s?k=nashville+tennessee+travel+guide&tag=rabbitholevid-20", videos: ["Nashville complete guide", "Broadway honky tonks", "Nashville food tour", "Country music hall fame", "Budget Nashville tips", "Nashville day trips", "Hot chicken guide", "Nashville nightlife", "Nashville hidden gems", "Nashville travel tips"] },
  { slug: "peru-cusco", emoji: "🏔", name: "Cusco", country: "Peru", region: "americas", tier: "silver", views: "3.4B", bg: "#1a0800", desc: "Gateway to the Incas", bookingLink: "https://www.booking.com/searchresults.html?ss=Cusco+Peru&aid=2311236", tourLink: "https://www.getyourguide.com/cusco-l193/", gearLink: "https://www.amazon.com.au/s?k=cusco+peru+altitude+travel&tag=rabbitholevid-20", videos: ["Cusco complete guide", "Cusco altitude tips", "Sacred Valley tour", "Rainbow Mountain day trip", "Cusco food guide", "Budget Cusco travel", "Machu Picchu from Cusco", "Cusco markets guide", "Cusco hidden gems", "Cusco travel tips"] },

  // AFRICA & MIDDLE EAST
  { slug: "zanzibar", emoji: "🏝", name: "Zanzibar", country: "Tanzania", region: "africa", tier: "silver", views: "3.6B", bg: "#081820", desc: "Spice island paradise", bookingLink: "https://www.booking.com/searchresults.html?ss=Zanzibar+Tanzania&aid=2311236", tourLink: "https://www.getyourguide.com/zanzibar-l193/", gearLink: "https://www.amazon.com.au/s?k=zanzibar+tanzania+travel+snorkel&tag=rabbitholevid-20", videos: ["Zanzibar complete guide", "Stone Town tour", "Best beaches Zanzibar", "Zanzibar spice tour", "Nungwi beach guide", "Budget Zanzibar tips", "Zanzibar snorkelling", "Zanzibar food guide", "Zanzibar hidden gems", "Zanzibar travel tips"] },
  { slug: "rwanda", emoji: "🦍", name: "Rwanda", country: "Rwanda", region: "africa", tier: "silver", views: "2.4B", bg: "#081408", desc: "Land of a thousand hills", bookingLink: "https://www.booking.com/searchresults.html?ss=Rwanda&aid=2311236", tourLink: "https://www.getyourguide.com/rwanda-l193/", gearLink: "https://www.amazon.com.au/s?k=rwanda+gorilla+trekking+gear&tag=rabbitholevid-20", videos: ["Rwanda gorilla trekking", "Kigali city guide", "Rwanda genocide memorial", "Nyungwe forest trek", "Rwanda budget travel", "Gorilla permit guide", "Lake Kivu guide", "Rwanda food guide", "Rwanda hidden gems", "Rwanda travel tips"] },
  { slug: "mauritius", emoji: "🌺", name: "Mauritius", country: "Mauritius", region: "africa", tier: "silver", views: "2.8B", bg: "#081820", desc: "Island of dreams", bookingLink: "https://www.booking.com/searchresults.html?ss=Mauritius&aid=2311236", tourLink: "https://www.getyourguide.com/mauritius-l193/", gearLink: "https://www.amazon.com.au/s?k=mauritius+snorkel+beach+gear&tag=rabbitholevid-20", videos: ["Mauritius complete guide", "Best beaches Mauritius", "Mauritius budget travel", "Le Morne peninsula", "Mauritius food guide", "Snorkelling Mauritius", "Mauritius vs Maldives", "Port Louis city", "Mauritius hidden gems", "Mauritius travel tips"] },
  { slug: "oman", emoji: "🏜", name: "Oman", country: "Oman", region: "middleeast", tier: "silver", views: "3.1B", bg: "#1a1000", desc: "Arabia's best kept secret", bookingLink: "https://www.booking.com/searchresults.html?ss=Oman&aid=2311236", tourLink: "https://www.getyourguide.com/oman-l193/", gearLink: "https://www.amazon.com.au/s?k=oman+travel+guide+desert&tag=rabbitholevid-20", videos: ["Oman complete guide", "Muscat city guide", "Wahiba Sands desert", "Wadi Shab hike", "Oman budget travel", "Nizwa fort visit", "Oman vs UAE", "Oman food guide", "Oman hidden gems", "Oman travel tips"] },
  { slug: "georgia-country", emoji: "🍷", name: "Georgia", country: "Georgia", region: "middleeast", tier: "silver", views: "2.7B", bg: "#1a0808", desc: "Where Europe meets Asia", bookingLink: "https://www.booking.com/searchresults.html?ss=Tbilisi+Georgia&aid=2311236", tourLink: "https://www.getyourguide.com/tbilisi-l193/", gearLink: "https://www.amazon.com.au/s?k=georgia+tbilisi+travel+guide&tag=rabbitholevid-20", videos: ["Georgia country guide", "Tbilisi city tour", "Georgian wine guide", "Kazbegi mountain trek", "Georgia budget travel", "Batumi beach city", "Georgian food guide", "Old Tbilisi walk", "Georgia hidden gems", "Georgia travel tips"] },
  { slug: "abu-dhabi", emoji: "🕌", name: "Abu Dhabi", country: "UAE", region: "middleeast", tier: "silver", views: "4.2B", bg: "#1a1000", desc: "Capital of the Emirates", bookingLink: "https://www.booking.com/searchresults.html?ss=Abu+Dhabi&aid=2311236", tourLink: "https://www.getyourguide.com/abu-dhabi-l193/", gearLink: "https://www.amazon.com.au/s?k=abu+dhabi+uae+travel+guide&tag=rabbitholevid-20", videos: ["Abu Dhabi complete guide", "Sheikh Zayed mosque", "Abu Dhabi vs Dubai", "Louvre Abu Dhabi", "Budget Abu Dhabi tips", "Yas Island guide", "Abu Dhabi food tour", "Desert safari Abu Dhabi", "Abu Dhabi hidden gems", "Abu Dhabi travel tips"] },

  // OCEANIA
  { slug: "gold-coast", emoji: "🏄", name: "Gold Coast", country: "Australia", region: "oceania", tier: "silver", views: "3.9B", bg: "#081820", desc: "Sun surf and theme parks", bookingLink: "https://www.booking.com/searchresults.html?ss=Gold+Coast+Australia&aid=2311236", tourLink: "https://www.getyourguide.com/gold-coast-l193/", gearLink: "https://www.amazon.com.au/s?k=gold+coast+australia+travel&tag=rabbitholevid-20", videos: ["Gold Coast complete guide", "Surfers Paradise guide", "Gold Coast theme parks", "Best beaches Gold Coast", "Hinterland day trip", "Budget Gold Coast tips", "Gold Coast nightlife", "Gold Coast food guide", "Gold Coast hidden gems", "Gold Coast travel tips"] },
  { slug: "tasmania", emoji: "🐨", name: "Tasmania", country: "Australia", region: "oceania", tier: "silver", views: "2.6B", bg: "#0e1408", desc: "Australia's wild island", bookingLink: "https://www.booking.com/searchresults.html?ss=Tasmania+Australia&aid=2311236", tourLink: "https://www.getyourguide.com/tasmania-l193/", gearLink: "https://www.amazon.com.au/s?k=tasmania+australia+hiking+gear&tag=rabbitholevid-20", videos: ["Tasmania complete guide", "Cradle Mountain hike", "MONA museum Hobart", "Tasmania road trip", "Freycinet Peninsula", "Budget Tasmania tips", "Bruny Island tour", "Tasmania food guide", "Tasmania hidden gems", "Tasmania travel tips"] },
  { slug: "whitsundays", emoji: "⛵", name: "Whitsundays", country: "Australia", region: "oceania", tier: "gold", views: "3.4B", bg: "#081820", desc: "74 islands of paradise", bookingLink: "https://www.booking.com/searchresults.html?ss=Whitsundays+Australia&aid=2311236", tourLink: "https://www.getyourguide.com/whitsundays-l193/", gearLink: "https://www.amazon.com.au/s?k=whitsundays+sailing+snorkel&tag=rabbitholevid-20", videos: ["Whitsundays complete guide", "Sailing Whitsundays", "Whitehaven Beach guide", "Heart Reef flight", "Budget Whitsundays tips", "Best islands Whitsundays", "Snorkelling Whitsundays", "Airlie Beach guide", "Whitsundays hidden gems", "Whitsundays travel tips"] },
  { slug: "queenstown-nz", emoji: "🎿", name: "Queenstown", country: "New Zealand", region: "oceania", tier: "gold", views: "4.1B", bg: "#081020", desc: "Adventure capital of the world", bookingLink: "https://www.booking.com/searchresults.html?ss=Queenstown+New+Zealand&aid=2311236", tourLink: "https://www.getyourguide.com/queenstown-l193/", gearLink: "https://www.amazon.com.au/s?k=queenstown+nz+adventure+gear&tag=rabbitholevid-20", videos: ["Queenstown complete guide", "Bungee jumping Queenstown", "Milford Sound day trip", "Queenstown skiing guide", "Budget Queenstown tips", "Remarkables ski field", "Queenstown food guide", "Fiordland from Queenstown", "Queenstown hidden gems", "Queenstown travel tips"] },
  { slug: "cook-islands", emoji: "🌺", name: "Cook Islands", country: "Cook Islands", region: "oceania", tier: "silver", views: "1.8B", bg: "#081820", desc: "South Pacific gem", bookingLink: "https://www.booking.com/searchresults.html?ss=Cook+Islands&aid=2311236", tourLink: "https://www.getyourguide.com/cook-islands-l193/", gearLink: "https://www.amazon.com.au/s?k=cook+islands+snorkel+travel&tag=rabbitholevid-20", videos: ["Cook Islands guide", "Rarotonga island tour", "Cook Islands snorkelling", "Aitutaki lagoon cruise", "Budget Cook Islands", "Cook Islands vs Fiji", "Muri beach guide", "Cook Islands food", "Cook Islands hidden gems", "Cook Islands tips"] },
];

// Read existing destinations file
let content = fs.readFileSync('data/destinations.js', 'utf8');

// Remove the last line (export default destinations;) and closing bracket
content = content.replace(/\];\n\nexport default destinations;/, '');

// Add new destinations
const newContent = newDestinations.map(d => 
  `  { slug: "${d.slug}", emoji: "${d.emoji}", name: "${d.name}", country: "${d.country}", region: "${d.region}", tier: "${d.tier}", views: "${d.views}", bg: "${d.bg}", desc: "${d.desc}", bookingLink: "${d.bookingLink}", tourLink: "${d.tourLink}", gearLink: "${d.gearLink}", videos: ${JSON.stringify(d.videos)} }`
).join(',\n');

content = content + ',\n' + newContent + '\n];\n\nexport default destinations;\n';

fs.writeFileSync('data/destinations.js', content);
console.log('Done! Added', newDestinations.length, 'destinations');

// Verify count
const slugCount = (content.match(/slug: "/g) || []).length;
console.log('Total destinations:', slugCount);
